# Generated by Django 3.2 on 2023-04-14 03:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_unique_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(help_text='Логин должен содержать только буквы и цифры. Поле не может состоять из "me", содержать пробелы, слеши.', max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
