# Generated by Django 3.2 on 2023-04-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230420_0633'),
        ('reviews', '0002_auto_20230421_1521'),
    ]

    operations = [
    ]
